# Generated by Django 3.0.5 on 2020-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvideo',
            name='vid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
